/*
 * pg_builtin_ext.c — Built-in extension registry for static PG builds.
 *
 * In a statically-linked postgres binary, dlopen() can't load .so modules.
 * This file provides a function lookup table that dfmgr.c queries before
 * attempting file-based loading. If the requested library + symbol match
 * a built-in entry, we return the function pointer directly.
 *
 * Currently registers: PL/pgSQL (plpgsql)
 *
 * Usage: compile this file and link it into the postgres binary, then
 * apply the dfmgr.c sed patches that call pg_builtin_lookup().
 */

#include "postgres.h"
#include "fmgr.h"

/* PL/pgSQL entry points — defined in pl_handler.c */
extern Datum plpgsql_call_handler(PG_FUNCTION_ARGS);
extern Datum plpgsql_inline_handler(PG_FUNCTION_ARGS);
extern Datum plpgsql_validator(PG_FUNCTION_ARGS);

/* PL/pgSQL module init — called by _PG_init convention */
extern void _PG_init(void);

/* PG_FUNCTION_INFO_V1 info functions — generated by macro in pl_handler.c */
extern const Pg_finfo_record *pg_finfo_plpgsql_call_handler(void);
extern const Pg_finfo_record *pg_finfo_plpgsql_inline_handler(void);
extern const Pg_finfo_record *pg_finfo_plpgsql_validator(void);

typedef struct {
    const char *modname;
    const char *symname;
    void       *symptr;
} BuiltinExtEntry;

/*
 * Sentinel filehandle value for builtin modules.
 * Used to identify that a module was loaded from the builtin registry.
 */
static int _builtin_sentinel;
void *PG_BUILTIN_HANDLE = &_builtin_sentinel;

static const BuiltinExtEntry builtin_entries[] = {
    { "plpgsql", "plpgsql_call_handler",          (void *)plpgsql_call_handler },
    { "plpgsql", "plpgsql_inline_handler",        (void *)plpgsql_inline_handler },
    { "plpgsql", "plpgsql_validator",             (void *)plpgsql_validator },
    { "plpgsql", "_PG_init",                     (void *)_PG_init },
    /* PG_FUNCTION_INFO_V1 info records — needed by fetch_finfo_record */
    { "plpgsql", "pg_finfo_plpgsql_call_handler",   (void *)pg_finfo_plpgsql_call_handler },
    { "plpgsql", "pg_finfo_plpgsql_inline_handler", (void *)pg_finfo_plpgsql_inline_handler },
    { "plpgsql", "pg_finfo_plpgsql_validator",      (void *)pg_finfo_plpgsql_validator },
    { NULL, NULL, NULL }
};

/*
 * pg_builtin_lookup — check if a library/symbol pair is built-in.
 *
 * libname: library path or basename (e.g. "$libdir/plpgsql" or "plpgsql")
 * symname: function symbol (e.g. "plpgsql_call_handler")
 *
 * Returns function pointer if found, NULL otherwise.
 */
void *
pg_builtin_lookup(const char *libname, const char *symname)
{
    const char *bn;

    if (libname == NULL || symname == NULL)
        return NULL;

    /* Extract basename: strip path prefix */
    bn = strrchr(libname, '/');
    bn = bn ? bn + 1 : libname;

    /* Strip .so extension if present */
    {
        int len = strlen(bn);
        static char clean[256];
        if (len > 3 && strcmp(bn + len - 3, ".so") == 0 && len < 256)
        {
            memcpy(clean, bn, len - 3);
            clean[len - 3] = '\0';
            bn = clean;
        }
    }

    for (int i = 0; builtin_entries[i].modname; i++)
    {
        if (strcmp(bn, builtin_entries[i].modname) == 0 &&
            strcmp(symname, builtin_entries[i].symname) == 0)
            return builtin_entries[i].symptr;
    }
    return NULL;
}

/*
 * pg_builtin_lookup_sym — lookup a symbol by name across all builtin modules.
 * Used by lookup_external_function when the filehandle is a builtin sentinel.
 */
void *
pg_builtin_lookup_sym(const char *symname)
{
    if (symname == NULL)
        return NULL;
    for (int i = 0; builtin_entries[i].modname; i++)
    {
        if (strcmp(symname, builtin_entries[i].symname) == 0)
            return builtin_entries[i].symptr;
    }
    return NULL;
}

/*
 * pg_builtin_is_module — check if a library name is a built-in module.
 * Returns true if the module is in our registry (regardless of symbol).
 */
bool
pg_builtin_is_module(const char *libname)
{
    const char *bn;

    if (libname == NULL)
        return false;

    bn = strrchr(libname, '/');
    bn = bn ? bn + 1 : libname;

    {
        int len = strlen(bn);
        static char clean[256];
        if (len > 3 && strcmp(bn + len - 3, ".so") == 0 && len < 256)
        {
            memcpy(clean, bn, len - 3);
            clean[len - 3] = '\0';
            bn = clean;
        }
    }

    for (int i = 0; builtin_entries[i].modname; i++)
    {
        if (strcmp(bn, builtin_entries[i].modname) == 0)
            return true;
    }
    return false;
}
